apiVersion: cinder.openstack.org/v1beta1
kind: Cinder
metadata:
  name: cinder
  namespace: {{ .Namespace }}
spec:
  databaseHostname: mariadb
  cinderAPIReplicas: {{ .CinderAPIReplicas }}
  cinderSchedulerReplicas: {{ .CinderSchedulerReplicas }}
  cinderBackupReplicas: {{ .CinderBackupReplicas }}
  // TODO: for now hard code node selector to generig worker nodes
  cinderBackupNodeSelectorRoleName: worker
  cinderSecret: cinder-secret
  novaSecret: nova-secret
  cinderAPIContainerImage: quay.io/tripleotrain/centos-binary-cinder-api:current-tripleo
  cinderSchedulerContainerImage: quay.io/tripleotrain/centos-binary-cinder-scheduler:current-tripleo
  cinderBackupContainerImage: quay.io/tripleotrain/centos-binary-cinder-backup:current-tripleo
  cinderVolumes:
  - name: volume1
    databaseHostname: mariadb
    cinderVolumeContainerImage: quay.io/tripleotrain/centos-binary-cinder-volume:current-tripleo
    cinderVolumeReplicas: {{ .CinderVolumeReplicas }}
    // TODO: for now hard code node selector to generig worker nodes
    cinderVolumeNodeSelectorRoleName: worker
