apiVersion: glance.openstack.org/v1beta1
kind: GlanceAPI
metadata:
  name: glanceapi
  namespace: {{ .Namespace }}
spec:
  # Add fields here
  databaseHostname: mariadb
  replicas: {{ .GlanceReplicas }}
  storageClass: {{ .StorageClass }}
  storageRequest: 10G
  containerImage: quay.io/tripleotrain/centos-binary-glance-api:current-tripleo
  secret: glance-secret
